[package]
name = "rust-pad"
version = "0.10.4"
authors = ["Pedro Almeida <contact@pedroalmeida.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="2.0.3"
unicode-segmentation="1.8.0"
